config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @lists = List.all
  end
  
  def show
  end
  
  def new
    @list = List.new
  end
  
  def create
    @list = List.new(list_params)
    
    if @list.save
      flash[:succes] = 'タスクが正常に作成されました'
      redirect_to @list
      
    else 
      flash[:danger] = 'タスクが作成できませんでした'
      render :new
    end
      
  end
  
  def edit
  end
  
  def update
    
    if @list.update(list_params)
      flash[:succes] = 'タスクが正常に更新されました'
      redirect_to @list
    
    else
      flash[:danger] = 'タスクが更新されませんでした'
      render :edit
    end      
        
  end
  
  def destroy
    @list.destroy
    
    flash[:succes] = 'タスクは正常に削除されました'
    redirect_to lists_url
  end
  
  private
  
  def set_list
    @list = List.find(params[:id])
  end
  
  #Strong parameter
  def list_params
    params.require(:list).permit(:content, :title)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
     <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>

　<% if list.errors.any? %>
　<div id="error_explanation">
　  <ul>
　    <% list.errors.full_messages.each do |message| %>
　      <li><%= message %></li>
　    <% end %>
　  </ul>
　</div>
　<% end %>
　
　 <%= f.label :title, 'タイトル' %>
  <%= f.text_field :title %>

  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>
  
  <%= f.submit '投稿' %>
<% end %>

app/views/lists/edit.html.erb
<h1>id: <%= @list.id %>のタスクの編集</h1>

<%= render 'form', list: @list %>

<%= link_to '一覧に戻る', lists_path %>

app/views/lists/index.html.erb
<h1>タスクリスト一覧</h1>

<ul>
  <% @lists. each do |list| %>
  <li><%= link_to list.id, list %> : <%= list.title %> > <%= list.content %></li>
  <% end %>
</ul>

<%= link_to '新規タスクの追加', new_list_path %>

app/views/lists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', list: @list %>

<%= link_to '一覧に戻る', lists_path %>
  

app/views/lists/show.html.erb
<h1><%= @list.id %>のタスク詳細ページ</h1>

<p>タイトル:<%= @list.title %></p>
<p>タスク:<%= @list.content %></p>

<%= link_to '一覧に戻る', lists_path%>
<%= link_to 'このタスクを編集する', edit_list_path(@list) %>
<%= link_to 'このタスクを削除する', @list, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>